spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roomescape?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.hbm2ddl.auto: create-drop
      format_sql: true

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

payment:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
